getsentry/arroyo

- setup.py
`arroyo` seems to be unavailable on PyPI. Let's try renaming to
`sentry-arroyo`.
> build: Rename package to sentry-arroyo

- CHANGELOG.md
- arroyo/processing/strategies/streaming/factory.py
- arroyo/processing/strategies/streaming/transform.py
This adds an optional `initializer` argument to the parallel transform step
which allows a custom initialization function to be run when a process is
spawned. The custom initialize function can also be provided via the
ConsumerStrategyFactory.
The primary motivation for this is to allow Snuba to pass a function that
sets up the Sentry SDK immediately when a process is spawned so that
any logs or errors can be reported to Sentry.
This should not be included in the `0.0.1` release
> feat: Parallel transform step accepts optional initializer function

- arroyo/processing/processor.py
- tests/backends/mixins.py
If drop_failed_messages is passed to the StreamProcessor it immediately drops
a message that fails processing once.
> feat: Drop events that fail processing

- arroyo/processing/processor.py
- tests/backends/mixins.py
This reverts commit e5e1746e66ea6c22d513b8880015a3e57177877b.
The commit being reverted was not intended to be permanent; it
was a quick hack to deal with invalid messages that failed processing
by just skipping them alltogether. We never ended up releasing this
code or skipping messages so let's revert.
> Revert "feat: Drop events that fail processing (#26)"

- arroyo/backends/abstract.py
- arroyo/backends/kafka/consumer.py
- arroyo/backends/local/backend.py
- arroyo/processing/processor.py
- arroyo/processing/strategies/abstract.py
- arroyo/processing/strategies/batching.py
- arroyo/processing/strategies/streaming/collect.py
- arroyo/processing/strategies/streaming/factory.py
- arroyo/synchronized.py
- arroyo/types.py
- arroyo/utils/profiler.py
- tests/backends/mixins.py
- tests/processing/strategies/test_streaming.py
This is one of the least invasive ways I've found so far to make the
timestamp associated with an offset availble to the collector processing step.
The end goal of this is to allow Snuba to produce that timestamp to the commit log
during the commit offsets phase, so that it can later be used for subscription scheduling.
We already keep track of the hi and lo offset for each batch and use that to commit offsets.
With this change we will also keep track of the associated timestamp together with it's
corresponding offset number.
> feat: Keep track of timestamps together with offsets in a batch

- arroyo/synchronized.py
- tests/backends/test_kafka.py
- tests/test_synchronized.py
Commit now contains a orig_message_ts field which is serialized
as part of the Kafka payload headers.
> feat: Add orig_message_ts to Commit and commit_codec

- arroyo/processing/strategies/streaming/transform.py
- tests/processing/strategies/test_streaming.py
This is meant to have a metric that provides the number of processes to be used to normalize other metrics.
Example:
We have the number of processes being actively in use at a given point in time. This can be used both as a utilization and as a saturation metric if we had the number of available process as well. So we can have alert on the amount of processes in use vs the total.
> feat(metrics) Add a gauge set to the number of running processes

- arroyo/processing/strategies/batching.py
We do not have a metric on the number of items in the batch during flush and on the time between two flushes.
> perf(metrics) Add some metrics to the batching consumer

- arroyo/synchronized.py
Lately we observed weird temporary increases in subscriptions consumer latency on selected partitions.
It is hard to understand exactly who is causing them. 
One theory is that somehow the commit log messages could be delayed or could be processed too late by the subscriptions consumer. 
Adding latency metrics to the code that consumes the commit log to rule out this hypothesis.
Specifically we record both the difference between the current time and the broker time the commit log message was produced at and the difference between the current time and the broker timestamp of the last message the commit log messages refers to.
The first gives us an indication if the commit log messages are late.
The second gives us an indication if the main consumer is consuming old messages.
> feat(perf) Add latency metrics to the messages coming from the commit log

- arroyo/processing/processor.py
- arroyo/processing/strategies/streaming/collect.py
- arroyo/processing/strategies/streaming/transform.py
We ran into a few race conditions during consumer termination. 
This is hard to troubleshoot without knowing where the processor hangs. 
This pr increases a bit the log level of some messages logged during the termination process.
> fix(logs) Increase log level during termination.

- arroyo/processing/strategies/streaming/__init__.py
- arroyo/processing/strategies/streaming/collect.py
- arroyo/processing/strategies/streaming/factory.py
- tests/processing/strategies/test_streaming.py
Since the multi storage consumer has its own factory we need to export
ParallelCollectStep. Also addressed the comments from the previous
PR https://github.com/getsentry/arroyo/pull/41
> chore(parallel_collect): Allow importing ParallelCollectStep

- arroyo/processing/strategies/dead_letter_queue/__init__.py
🤮 `from arroyo.processing.strategies.dead_letter_queue.policies.abstract import InvalidMessage`
😎 `from arroyo.processing.strategies.dead_letter_queue import InvalidMessage`
> fix(dlq): Export InvalidMessage from DLQ

- arroyo/processing/strategies/dead_letter_queue/dead_letter_queue.py
- arroyo/processing/strategies/dead_letter_queue/policies/abstract.py
- arroyo/processing/strategies/dead_letter_queue/policies/count.py
- arroyo/processing/strategies/dead_letter_queue/policies/ignore.py
- arroyo/processing/strategies/dead_letter_queue/policies/raise_e.py
A DLQ Policy does not care about the Payload type of a Message.
Originally a Policy itself would take the message as a parameter and the signature for the handler looked like: `handle_invalid_message(message: Message[TPayload], e: InvalidMessage)`.
That was changed in favor of just having the exception itself hold the message. Removing the generic was forgotten about when the signature changed to `handle_invalid_message(e: InvalidMessage)`.
> fix(dlq): Removed Generic payload from DLQ Policy

- arroyo/backends/kafka/consumer.py
- tests/backends/mixins.py
- tests/backends/test_kafka.py
KafkaConsumer now supports the `cooperative-sticky` partitioning strategy.
The goal of this change is to try and reduce the amount of unnecessary rebalances
that happen during Kubernetes rolling deployments.
> feat(consumer): Support incremental cooperative rebalancing

- requirements.txt
librdkafka 1.7.0 includes improvements to the sticky assignor
> feat: Bump confluent-kafka-python to 1.7.0

- arroyo/processing/strategies/streaming/factory.py
- `ConsumerStrategyFactory` builds the main strategy used by all consumers in Snuba
- Optionally pass a DLQ policy to the Consumer Strategy Factory
- This will wrap the strategy with a DLQ with the given policy
Here's an example of how this will be used:
https://github.com/getsentry/snuba/pull/2585
> feat(consumer): Wrap consumer strategy with DLQ if it exists

- tests/backends/mixins.py
This test frequently fails since it often takes longer than 1 second for
the consumer to poll for the message in CI. Increase the time that
poll() will wait for a message.
> test: Fix flaky test

- arroyo/processing/processor.py
If the assignment or revocation callback is called with no partitions
we don't need to close and recreate the processing strategy. This
happens frequently with incremental rebalancing.
> feat: Avoid unnecessarily recreating processing strategy

- arroyo/backends/local/backend.py
- arroyo/processing/strategies/dead_letter_queue/__init__.py
- arroyo/processing/strategies/dead_letter_queue/dead_letter_queue.py
- arroyo/processing/strategies/dead_letter_queue/policies/abstract.py
- arroyo/processing/strategies/dead_letter_queue/policies/count.py
- arroyo/processing/strategies/dead_letter_queue/policies/ignore.py
- arroyo/processing/strategies/dead_letter_queue/policies/produce.py
- arroyo/processing/strategies/dead_letter_queue/policies/raise_e.py
- tests/processing/strategies/test_dead_letter_queue.py
I'm not sure if I did this correctly but eventually our DLQ policies need to produce invalid messages to a dead letter topic.
- Introduced a new Policy which has the sole purpose of producing a given message to a dead letter topic
- This could be extended by other policies such as the count policy to start putting the invalid messages into the dead letter topic instead of just ignoring them
- Modified `InvalidMessage` Exception to also hold the original topic the message was produced to along with the timestamp the exception was thrown
> feat(dlq): Added produce policy

- arroyo/backends/abstract.py
- arroyo/backends/kafka/configuration.py
- arroyo/backends/kafka/consumer.py
- arroyo/backends/local/backend.py
- arroyo/processing/strategies/batching.py
- arroyo/processing/strategies/streaming/transform.py
- arroyo/synchronized.py
- tests/backends/test_kafka.py
- tests/processing/strategies/test_dead_letter_queue.py
Adds a flag to disable the special handling for auto offset resets in arroyo. When the made up `force.offset.reset` flag is set to `True` (defaults to `False`) then the auto offset reset error is not converted into a `OffsetOutOfRange` exception.
Refs https://github.com/getsentry/snuba/pull/2573
> feat: Add flag to restore confluence kafka auto.offset.reset behavior

- arroyo/processing/strategies/dead_letter_queue/dead_letter_queue.py
- arroyo/processing/strategies/dead_letter_queue/policies/abstract.py
- arroyo/processing/strategies/dead_letter_queue/policies/count.py
- arroyo/processing/strategies/dead_letter_queue/policies/ignore.py
- arroyo/processing/strategies/dead_letter_queue/policies/produce.py
- arroyo/processing/strategies/dead_letter_queue/policies/raise_e.py
- arroyo/processing/strategies/streaming/factory.py
- The produce policy takes in a producer which is never closed, this leaves the consumer hanging on shutdown
- Added `self.__producer.close()` to the produce policy join method, this fixes the hanging issue
- The produce policy takes in a producer which is not recreated upon consumer rebalancing
- Introduced the policy closure to the Consumer Strategy Factory in order to recreate the policy entirely every time the create() method is called (eg when rebalancing)
- Introduced `close()` and `terminate()` methods to Policies to be used when DLQ is closed/terminated
> fix(dlq): Policy closure added + Producer closed

- CHANGELOG.md
- arroyo/processing/strategies/streaming/factory.py
"Closure" isn't a clear enough term for what the function is actually doing, which is creating the policy object.
https://github.com/getsentry/snuba/pull/2717#discussion_r877329486
> refactor(dlq): Renamed policy "closure" to policy "creator"

- arroyo/processing/strategies/dead_letter_queue/dead_letter_queue.py
- tests/processing/strategies/test_dead_letter_queue.py
- A processing strategy's `join()` method may raise `InvalidMessages`
- DLQ currently doesn't catch that, it happened here: https://sentry.io/organizations/sentry/issues/3385232274/
- Updated DLQ to catch and handle it
> fix(dlq): Join method did not handle InvalidMessages

- examples/transform_and_produce/Dockerfile
- examples/transform_and_produce/README.md
- examples/transform_and_produce/docker-compose.yml
This pull adds a docker-compose convenience script for testing the Arroyo project.  It is decoupled from Sentry and contains documentation for running the example.
Notes:
* I wanted to simplify the process further by running the Arroyo script within the docker-compose.yml file.  However, it seems the Arroyo example causes Kafka to crash if it's not ready to receive connections.
* The script doesn't perfectly mirror our CI.  The ports are different and LISTENERs have been tweaked but it is mostly similar and broadly applies.
> feat: Add docker-compose orchestrated example script

- requirements.txt
this doesn't change what actual version gets installed -- but allows downstreams to change the version without having to go through the release pipeline here
> adjust confluent-kafka version to >=

- .github/workflows/docs.yml
We need to run the docs when we push on `main` not `master`. 
I had copied it from Snuba.
> fix(docs) Fix branch name on GHA

- Makefile
- arroyo/processing/strategies/streaming/collect.py
- arroyo/processing/strategies/streaming/factory.py
The parallel collect thread timeout was hardcoded. 
A consumer started hitting it and crashlooping.
This sets it as a parameter
> fix(collector) Add parallel collect timeout

- arroyo/backends/kafka/commit.py
- arroyo/commit.py
- arroyo/processing/processor.py
- arroyo/processing/strategies/abstract.py
- arroyo/synchronized.py
- arroyo/types.py
- arroyo/utils/profiler.py
- docs/source/getstarted.rst
- tests/backends/test_commit.py
- tests/backends/test_kafka.py
- tests/processing/test_processor.py
- tests/test_commit.py
This is an attempt to simplify throttling commits in consumers. Generally speaking it is not safe for high throughput consumers to commit every offset. Today in order to achieve this with Arroyo, every consumer needs to manually implement throttling by themselves (unless batching is being used). This is verbose and easy to get wrong. This change aims to make it easier to do the right thing.
With this change, the stream processor takes an optional commit policy argument. The commit policy specifies the minimum time or minimum messages between commits.
In order to avoid throttling during shutdown, the commit function also now supports a force flag to override the commit policy / throttling behavior. This should be passed during consumer shutdown sequence as we no longer want to throttle in …
> feat: Introduce commit policies

- .github/workflows/ci.yml
Python 3.10 should be supported now by confluent-kafka-python
> build: Run CI on Python 3.10

- arroyo/processing/strategies/dead_letter_queue/invalid_messages.py
Technically this can be plugged into any backend, not just kafka. It only represents a message in a group of messages that failed at a processing step.
> ref: Rename variable

- arroyo/processing/processor.py
- tests/processing/strategies/test_batching.py
- tests/processing/test_processor.py
The purpose of this change is to provide some common basic metrics for all Arroyo consumers to help better understand consumer performance and break down where time is being spent.
Specifically 3 timings are being provided:
- `arroyo.consumer.poll.time` - Time spent in poll. Higher if the librdkafka buffer is empty
- `arroyo.consumer.processing.time` - Time spent in strategy submit and poll methods together
- `arroyo.consumer.paused.time` - Time spent in backpressure where consumer is paused
> feat: Add stream processor metrics

- tests/backends/test_commit.py
This test was unnecessarily complex. There is no reason to involve a fake broker and producer when all we are doing is testing that encoding and decoding a message works correctly and we get the same value back after it is decoded.
> test: Simplify the commit codec test

- tests/processing/strategies/test_collect.py
- tests/processing/strategies/test_transform.py
These are the last of the strategies whose tests were all grouped together in the test_streaming.py file. Now each strategy has it's own set of tests.
None of the actual tests have changed here. Just moving them into the right files.
> test: Split the collect and transform tests into separate files

- arroyo/types.py
- tests/test_types.py
All of these common types should be pickleable. Since we expect the user might be passing Position around and manually passing it to the commit function, let's make it pickleable.
This is the workaround described in https://github.com/python/cpython/issues/80605
> fix: Make Position pickleable

- arroyo/processing/processor.py
- tests/processing/test_processor.py
Commit policies make decisions based on the number of messages
committed, but we're actually passing the number of commit calls we have
dropped since the last real commit.
> fix: Compute offset deltas for commit policy [SNS-1863]

- arroyo/processing/strategies/factory.py
This factory should not be part of Arroyo. It represents a very specific chain of processing steps that is too specific to the Snuba usage it was originally designed for and not generic enough for this library.
> feat: Mark ConsumerStrategyFactory/KafkaConsumerStrategyFactory deprecated

- arroyo/processing/strategies/commit.py
- arroyo/processing/strategies/produce.py
- arroyo/processing/strategies/run_task.py
- tests/processing/strategies/test_commit.py
- tests/processing/strategies/test_produce.py
- tests/processing/strategies/test_run_task.py
Since Arroyo supports building consumers with at least once guarantees, committing is always the last step in a chain of processing strategies after all other actions have completed.
Many of the processing steps today include committing offsets such as `ProduceAndCommit`, `RunTaskInThreads` and `BatchProcessingStrategy`. These strategies today can only be used as a last step in a chain. On the other hand, others take a `next_step` argument  which means another step must come afterward and they cannot be the last step.
This change aims make all of the other strategies more flexible by moving committing into a separate strategy. This strategy should be the only one ever used as the last strategy in a sequence. Every other strategy will take a `next_step` and can thus be used at any stage in …
> feat: Introduce separate commit strategy

- arroyo/processing/strategies/__init__.py
- arroyo/processing/strategies/transform.py
- examples/transform_and_produce/README.md
- examples/transform_and_produce/__init__.py
Now we have the `Produce` and `CommitOffsets` steps which can be easily chained together. We don't need `ProduceAndCommit` anymore.
Also updated the example to use `Produce` and `CommitOffsets`.
> feat: Remove ProduceAndCommit

- arroyo/processing/processor.py
There were a couple of incidents recently where consumers appeared to get stuck during shutdown. We were not sure exactly where things got stuck since these messages were only logged at debug level. Increase the level to INFO.
> feat: Increase log level during consumer shutdown

- arroyo/processing/strategies/abstract.py
There was some misunderstanding about when this exception should be raised. Add a docstring to help clarify.
> docs: Add docstring for MessageRejected

- arroyo/processing/strategies/batching.py
- tests/processing/strategies/test_batching.py
Removes the BatchProcessingStrategyFactory from Arroyo. Eventually the underlying BatchProcessingStrategy and AbstractBatchWorker should be removed too, but these are still being used so we need to allow more time for deprecation of those.
> feat: Remove BatchProcessingStrategyFactory from Arroyo

- arroyo/backends/abstract.py
- arroyo/backends/kafka/consumer.py
- arroyo/backends/local/backend.py
- arroyo/backends/local/storages/abstract.py
- arroyo/backends/local/storages/file.py
- arroyo/backends/local/storages/memory.py
- arroyo/processing/processor.py
- arroyo/processing/strategies/batching.py
- arroyo/processing/strategies/collect.py
- arroyo/processing/strategies/dead_letter_queue/policies/produce.py
- arroyo/processing/strategies/produce.py
- arroyo/processing/strategies/run_task.py
- arroyo/processing/strategies/transform.py
- arroyo/types.py
- examples/transform_and_produce/__init__.py
- tests/backends/mixins.py
- tests/backends/test_commit.py
- tests/backends/test_kafka.py
- tests/processing/strategies/test_batching.py
- tests/processing/strategies/test_collect.py
- tests/processing/strategies/test_commit.py
- tests/processing/strategies/test_dead_letter_queue.py
- tests/processing/strategies/test_filter.py
- tests/processing/strategies/test_produce.py
- tests/processing/strategies/test_run_task.py
- tests/processing/strategies/test_transform.py
- tests/processing/test_processor.py
- tests/test_types.py
This is an attempt to address the problems described in https://github.com/getsentry/arroyo/issues/125. It would be a major breaking change of Arroyo's API.
Today the `Message` interface is tied to a specific broker message (with a single partition, offset and timestamp). This doesn't make a lot of sense for strategies where the Message does not actually represent a single message but a batch of messages that have been grouped together - or, really, any scenario where a message no longer maps cleanly to a single underlying message from the Kafka broker.
This solution involves splitting the `Message` interface apart into `Message` and `BrokerPayload` to better serve the two distinct purposes. Now `Message` only has a `committable` property which is a mapping of partitions and offsets. This …
> feat: Split the Message interface to better support batching steps

- arroyo/processing/strategies/__init__.py
- arroyo/processing/strategies/run_task.py
- arroyo/processing/strategies/transform.py
- docs/source/strategies.rst
- tests/processing/strategies/test_run_task.py
- tests/processing/strategies/test_transform.py
This is the most basic strategy that Arroyo provides. The rationale behind this addition is to make the library even simpler and reduce the amount of boilerplate for simple use cases.
Specifically, I've noticed that many people are using the BatchProcessingStrategy and AbstractBatchWorker combination almost exclusively for non batching use cases, purely because it allowed for using Arroyo without requiring a custom processing strategy. This is supposed to provide an easy replacement in those scenarios that doesn't have the downside of
unnecessarily waiting for batches to get filled.
This implementation is almost identical to the previous transform step, however RunTask explicitly allows for side effects. Now TransformStep is simply an alias for RunTask which is kept for backward …
> feat: Add RunTask strategy

- arroyo/processing/processor.py
- tests/processing/test_processor.py
The first argument to should_commit is a duration/timedelta, not an
absolute timestamp.
This might explain why we are seeing severe performance regression when
using commit policy.
Some tests are failing, but i wanted to open this PR early on to get
some validation that i'm not totally confused?
> fix(commit_policy): Calculate elapsed timerange correctly

- arroyo/processing/strategies/commit.py
- tests/processing/strategies/test_commit.py
`CommitOffsets` can accept any message payload, since it doesn't do anything with it anyway. This removes the need for users to provide unnecessary type hinting when using the CommitOffsets policy.
> ref: Improve typing of CommitOffsets strategy

- docs/source/architecture.rst
RunTask, RunTaskInThreads, RunTaskWithMultiprocessing are designed to be the most approachable strategies in the library. Let's mention these in the strategies doc.
> docs: Call out the run task strategy

- tests/processing/test_processor.py
Since https://github.com/getsentry/arroyo/pull/134 consumer.poll() returns a BrokerValue and not a Message. For some reason, these tests were still passing even though they were still returning the old type.
> test: Fix streamprocessor tests

- arroyo/processing/strategies/decoder.py
- tests/processing/strategies/test_decoder.py
We want to be able to use the same JsonCodec in scenarios where we have a schema as well as scenarios where a topic schema is not yet available. This change makes schema optional. Validation function always returns true if no schema is provided.
> feat(decoders): Json decoder can be used without schema

- .gitignore
- Makefile
- arroyo/backends/kafka/consumer.py
- arroyo/backends/local/backend.py
- arroyo/commit.py
- arroyo/processing/processor.py
- pytest.ini
- requirements-test.txt
- tests/backends/mixins.py
- tests/processing/test_processor.py
- tests/test_commit.py
in QE environment, looking at the metrics in https://github.com/getsentry/sentry/pull/42291 show that using commit policies as part of https://github.com/getsentry/sentry/pull/41664 show a slowdown from avg 1 microsecond to 10 microseconds on every `Processor.commit` call
this PR moves a bunch of expensive logic from staging into commit to make the common case of not-committing faster, and skips a bunch of logic related to counting offsets if message-based commit policy is not configured
the result is that we are now at 4 microseconds avg instead, with the commit pre-master merge where #165 wasn't applied yet. I cannot test with that change because sentry fails to import Position then
the benchmarks only run once by default. to enable them, pass either `--benchmark-enable` to pytest to …
> ref(commit_policy): Improve performance of commit policy

- arroyo/processing/strategies/decoder.py
- mypy.ini
- requirements.txt
- tests/processing/strategies/serializers/test.avsc
- tests/processing/strategies/serializers/test.schema.json
- tests/processing/strategies/test_decoder.py
This change adds decoders for msgpack and avro alongside json (which already existed in the library).
Since Arroyo is supposed to be agnostic of the message serialization format, we want to support as many different formats as possible here.
> feat(serializers): Add more decoders

- Makefile
- arroyo/processing/strategies/decoder/__init__.py
- arroyo/processing/strategies/decoder/avro.py
- arroyo/processing/strategies/decoder/base.py
- arroyo/processing/strategies/decoder/json.py
- arroyo/processing/strategies/decoder/msgpack.py
- requirements.txt
- setup.py
These are only needed if the user is using this strategy and a particular encoding format, and are likely not needed by the majority of users.
> build: Make json, msgpack and avro optional dependencies

- arroyo/processing/strategies/decoder/__init__.py
- tests/processing/strategies/test_decoder.py
So it is possible to import use each of the codecs independently without including all of the optional dependencies.
> build: Split avro, json, msgpack into separate modules

- arroyo/processing/strategies/dead_letter_queue/dead_letter_queue.py
- arroyo/processing/strategies/filter.py
- arroyo/processing/strategies/run_task.py
We do this inconsistently, let's simply import this as ProcessingStrategy everywhere without the alias.
> ref: Don't alias ProcessingStrategy as ProcessingStep

- arroyo/processing/strategies/produce.py
The next step must be closed in Produce's join() method, not close() since join() attempts to continue submitting messages to the next step if they are pending. This will not be possible if the next step is closed.
> fix(produce): Fix closing next step

- arroyo/processing/strategies/decoder/__init__.py
Fixes a bug where all optional dependencies had to be installed if any was used. Now json, msgpack and avro can be installed and used independently.
> fix(decoder): Fix importing optional dependencies

- arroyo/processing/processor.py
This was added for incremental rebalancing where multiple assignments could happen without corresponding recovaction being first completed, but should never happen now that option was removed. Log an exception if it ever does.
> feat: Log exception if processing strategy exists on assignment

- arroyo/processing/processor.py
This change allows the user to configure the join timeout of a consumer strategy.
Currently, the timeout is hardcoded to None. The implication of this is that consumers can take a long time to finish rebalancing. This time may stack up, especially during deployments where multiple rebalancings will occur back to back as consumers are gradually rolled out and shut down. In some scenarios, it may be better to abandon in-flight messages and just immediately shut down.
This change keeps same default as before, but now consumers can pass a custom strategy join timeout if they want recovation callbacks to finish faster.
> feat: Configurable strategy join timeout

- arroyo/processing/strategies/run_task.py
We weren't catching the TimeoutError, leading to consumer to crash during join anytime the timeout is hit.
> fix: Fix multiprocessing join

- arroyo/processing/strategies/run_task.py
- tests/processing/strategies/test_run_task.py
This was likely a copy-paste job from poll() while trying to fix merge
conflicts in https://github.com/getsentry/arroyo/pull/185
That PR inadvertently changed the code to be the same as in `poll()`, this PR restores the previous code.
> fix(run_task): Fix bug where join() would not actually wait for tasks

- arroyo/processing/strategies/__init__.py
- arroyo/processing/strategies/batching.py
- arroyo/processing/strategies/unfold.py
- docs/source/strategies.rst
- tests/processing/strategies/test_batching.py
- tests/processing/strategies/test_unfold.py
This strategy is the opposite of Reduce. The objective is to provide a more flexible way to extract a number of messages from a single message than UnbatchStep currently allows. With UnbatchStep, the input message must be `ValuesBatch`, which is an array of BaseValue from the BatchStep. Unfold allows for any user defined type and user provided generation function.
This change is motivated by a recent attempt to use Batch/Unbatch in the Sentry indexer (https://github.com/getsentry/sentry/pull/44721). The other strategies in the pipeline expected a slightly different format to what the BatchStep outputs. Switching out single steps in this pipeline without changing the rest would be easier if we were able to define both custom fold and unfold functions.
> feat: Add unfold strategy

- arroyo/processing/strategies/run_task.py
Noticed this when working on the DLQ feature. RunTask and RunTask in threads take a next_step which is `ProcessingStrategy[Union[FilteredPayload, TResult]]` but RunTaskWithMultiprocessing did not. Not sure if there was a reason for the difference. This PR brings the API for all of these strategies in line.
> fix: RunTaskWithMultiprocessing support for filtered message

- arroyo/dlq.py
- tests/test_dlq.py
If commit isn't being called regularly, it may grow too large, let users configure the buffer size.
> feat: Make DLQ buffer size configurable

- arroyo/processing/processor.py
Let's prevent excessive calls to pause if we are already paused anyway.
> fix: Prevent repeated calls to consumer.pause() if already paused

- docs-requirements.txt
Seems like the extra got randomly renamed in an effort to modernize
packaging: https://github.com/tox-dev/sphinx-autodoc-typehints/issues/263
Also relax requirements on sphinx so that there's no dep conflict
> fix: Fix installation of sphinx-autodoc-typehints

- arroyo/processing/strategies/run_task_in_threads.py
- tests/processing/strategies/test_all.py
- tests/processing/strategies/test_guard.py
Follow up to https://github.com/getsentry/arroyo/pull/217. Ports the same fix for `RunTaskInThreads`.
Adds a test for `RunTask`, `RunTaskInThreads`, and `RunTaskWithMultiprocessing`.
> fix: Fix RunTaskInThreads to handle InvalidMessage during close, add tests

- arroyo/processing/strategies/reduce.py
- docs-requirements.txt
- docs/source/conf.py
- docs/source/index.rst
- docs/source/strategies.rst
while working on https://github.com/getsentry/arroyo/pull/220:
* swap out the docs theme for a nicer one
* remove a bunch of autogenerated documentation that isn't useful to
arroyo users (join(), close(), MessageBatch)
* remove documentation for legacy DLQs, decoders, encoders and
TransformStep. Codecs kind of moved into sentry-kafka-schemas,
decoders and encoders ended up not being used (and also reference
arroyo's own codecs), transform step is an alias for RunTask.
* Fix broken mermaid diagrams by upgrading the library
> ref: Clean up documentation

- arroyo/processing/strategies/run_task_with_multiprocessing.py
- pytest.ini
- tests/assertions.py
- tests/conftest.py
- tests/processing/strategies/test_run_task_with_multiprocessing.py
I am investigating an issue where increasing the buffer size increased consumer lag, e2e latency metrics and avg batch size. Turns out that this behavior is intentional, and we just have to document it better and add instrumentation.
> fix: Add metrics around RunTaskWithMultiprocessing + docs [SNS-2204]

- arroyo/processing/processor.py
Adds more logging when partitions are revoked to know what is happening during a consumer shutdown
> chore(processor): Add more logging

- arroyo/processing/processor.py
- arroyo/utils/logging.py
- tests/backends/test_kafka.py
- tests/conftest.py
- tests/processing/test_processor.py
When the consumer is crashing, we are terminating the strategy in
`StreamProcessor.run`. Later, rdkafka does partition revocation. At that
point the strategy is already None.
I currently believe this behavior has been there since a very long time
and does not cause any practical issues in production we are currently
seeing (such as consumers stalling and not processing any messages), and
rather that we are seeing this as a side-effect of exception logging in
rdkafka callbacks having been improved recently.
However, we are seeing this exception now in Sentry, and it should be
fixed.
> fix: Do not log error when consumer is already crashing

- arroyo/dlq.py
- arroyo/processing/processor.py
- tests/test_dlq.py
Previously processing invalid messages was very slow since each message was produced one a time and blocks until it is done. This change allows the producer to do some batching of messages to be produced, and only waits for messages to be produced prior to committing, or if there are too many pending messages enqueued.
> perf(dlq): Improve performance when there are many invalid messages

- arroyo/processing/strategies/run_task_with_multiprocessing.py
- tests/processing/strategies/test_run_task_with_multiprocessing.py
The output overflow metric gets emitted whenever next_step raises
MessageRejected, and that can be misleading.
> fix: Distinguish between backpressure and output overflow

- arroyo/processing/processor.py
- arroyo/processing/strategies/run_task_with_multiprocessing.py
- arroyo/utils/metrics_buffer.py
- tests/processing/test_processor.py
- tests/utils/test_metrics_buffer.py
Move MetricsBuffer out of processor module and extend it so it can
record min/max/avg/sum/count. All of those aggregates are opt-in.
Then, use it in multiprocessing strategy to record two new metrics about
min/max/avg item sizes: pickling size, and buffer size
As part of this, all consumer duration metrics emitted by the processor
are now suffixed with `.buffered_sum`.
> feat: add more item size stats to multiprocessing (and metrics refactor)

- docs/source/architecture.rst
- docs/source/getstarted.rst
- docs/source/what_for.rst
Spacing, invalid code blocks, unified indents, added `timeout=` to make it obvious what that `0` actually is.
> docs: Minor readability details

- arroyo/processing/strategies/run_task_with_multiprocessing.py
- arroyo/types.py
- tests/processing/strategies/test_run_task_with_multiprocessing.py
`Pool.join` will block for more than `timeout` seconds if there is a task that takes more than `timeout` seconds. We can just terminate the pool though, because we have effectively reimplemented `join()` ourselves using `__check_for_results`.
Note that when I say "task", I mean "task" from the POV of `multiprocessing`, which translates to a call to `apply_async`, which is an entire message batch from arroyo POV
This effect is potentially made worse if `next_step` is rejecting all messages:
* When running `git checkout origin/main arroyo/`, the new tests hang forever in join, because the batch keeps getting reprocessed
* When additinally removing `side_effect = MessageRejected()` from the new tests, they fail because `join()` "only" terminates whenever the pool is drained, which is 10 …
> fix(multiprocessing): Honor join() timeout even if processing pool is overloaded [INC-378]

- arroyo/processing/strategies/run_task_with_multiprocessing.py
- arroyo/types.py
- tests/processing/strategies/test_run_task_with_multiprocessing.py
Do not resubmit a batch when next_step raises MessageRejected. We can easily implement that now because we had to do something similar for DLQing
Batches are still re-serialized when output buffer overflows, so that can still have catastrophic perf impact.
Depends on a refactoring made in #237 
There is no strong evidence that this is the culprit of the problems we have in INC-378, such as lack of CPU saturation. However, we know two things:
* We are constantly dissatisfied with throughput of our consumers
* Due to recently added metrics, we know that snuba generic-metrics keeps encountering backpressure from http step towards multiprocessing step
Because of (2), IMO this performance bottleneck must be a major contributor to (1)
If there is continuous MessageRejected, it could be that we …
> fix(multiprocessing): More performant backpressure [INC-378]

- arroyo/processing/strategies/run_task_in_threads.py
We weren't catching the timeout error which was causing the consumer to crash unnecessarily instead of shutting down cleanly
> fix(run-task-in-threads): Fix shutdown

- arroyo/processing/strategies/run_task_in_threads.py
There's no "result" available if we hit the timeout error
> fix: Fix run task in threads (again)

- arroyo/processing/processor.py
- arroyo/utils/metric_defs.py
- arroyo/utils/metrics.py
- docs-requirements.txt
- docs/source/conf.py
- docs/source/metrics.rst
- docs/source/strategies/index.rst
- tests/metrics.py
- tests/utils/test_metrics.py
Register all metrics in the entire codebase in a Literal, and put
the literal in docs.
This is a bit less overhead than a global enum and requires fewer
changes in strategies that already pass metrics as strings.
> ref: Global metrics registry

- arroyo/utils/metrics.py
- tests/utils/test_metrics.py
There are some rare situations where we might want to reconfigure the metrics backend to something else after a while. This came up in the DLQ consumer code, which can be instructed to consume from multiple queues and apply different policies. In this scenario, we want to tag the metrics very differently each time.
> feat(metrics): Allow reconfiguring the metrics backend

- arroyo/processing/processor.py
- docs/source/backpressure.rst
This was done in https://github.com/getsentry/sentry/blob/43de083a4b874ab23de5db2c8f7f2958a3cb70ab/src/sentry/processing/backpressure/arroyo.py#L40, should probably be an Arroyo default
> feat: Avoid spinning on MessageRejected

- docs/source/architecture.rst
- docs/source/dlqs.rst
Dlq as a strategy doesn't exist anymore, remove the legacy doc. Hide some classes from the doc
> docs: Update dlq doc

- arroyo/processing/strategies/filter.py
- arroyo/utils/metric_defs.py
For https://github.com/getsentry/arroyo/issues/257 
It seemed to me that we should emit this metric in both scenarios, whether a CommitPolicy was passed in or not. Might have missed something though.
Also, if there are other metrics that would be helpful to add in `FilterStep` strategy, I can include them in this PR.
> metrics: Add metrics about dropped messages in FilterStep

- arroyo/processing/strategies/filter.py
- arroyo/processing/strategies/guard.py
- arroyo/processing/strategies/reduce.py
- arroyo/processing/strategies/run_task.py
- arroyo/processing/strategies/run_task_in_threads.py
- tests/processing/strategies/test_all.py
When a reduce strategy is terminated, the next strategy should also be
terminated.
We think that in INC-443, this caused the RunTaskInThreads in Snuba to
not be terminated at all, leaving us with background threads that
inhibited the shutdown of the process.
steps in snuba are:
* filterstep (optional)
* runtaskwithmultiprocessing (message processor)
* reduce (clickhouse write batch)
* runtaskinthreads (clickhouse write)
Also add more generic tests around close+join, and align arguments in
all strategies to be by-keyword so that the assertion passes.
> fix(reduce): Add missing call to next_step.terminate()

- arroyo/backends/kafka/configuration.py
Looks like this is in Sentry but not here. Seems safe to add here?
https://github.com/getsentry/sentry/blob/af54b69df3ed3b8beb5e945854d2e4f4c852a14d/src/sentry/utils/kafka_config.py#L17
> Add socket.timeout.ms to supported kafka configurations

- arroyo/processing/strategies/run_task_in_threads.py
- tests/processing/strategies/test_all.py
When using run_task_in_threads, the last batch of commits might be
dropped because poll() is not forwarded to the commit strategy.
This presents with the same exact symptoms as #259, but is only present
in consumers that use RunTaskInThreads.
> fix(run_task_in_threads): Commit offsets even when consumer is idle

- arroyo/processing/processor.py
- arroyo/processing/strategies/abstract.py
- tests/processing/test_processor.py
In sentry's unified consumers, there is no place to register a global
shutdown handler. Add this to arroyo directly in order to standardize
it, though technically there's no use for such a shutdown outside of
unified consumers since in other scenarios, the user manages the
lifecycle of the application themselves.
related to https://github.com/getsentry/arroyo/pull/277
> feat: Add global shutdown handler for strategy factory

- arroyo/processing/processor.py
Since `_run_once` can early return (https://github.com/getsentry/arroyo/blob/6286c7921978065edeb5ce72d829031f952d2e5e/arroyo/processing/processor.py#L369) it was possible that a message was never placed in `self.buffered_messages`. If we try to retreive it later, it can crash the consumer.
This is suspected to be the cause of the `Invalid message not found in buffer` messages we saw in prod.
> fix: Ensure carried over message is in buffer

- arroyo/processing/strategies/produce.py
- tests/processing/strategies/test_produce.py
If we get local queue full, let's raise MessageRejected to slow down the consumer.
> fix(produce): Apply backpressure instead of crashing

- arroyo/dlq.py
- tests/processing/strategies/test_run_task_with_multiprocessing.py
- tests/test_dlq.py
We saw a crash in the ingest spans consumer because InvalidMessage is unpickleable. Make it pickleable to avoid the crash.
This should fix https://sentry.sentry.io/issues/4473581085/?project=1
> fix(dlq): Make InvalidMessage pickleable

- arroyo/backends/kafka/consumer.py
Sometimes a program may have to shut down before the strategies are created. This producer thread starts running as soon as the producer is instantiated even before it is added to a strategy.  To simplify cleanup, make it a daemon thread so that it exists when the parent process exists and doesn't block exiting.
> Make producer thread a deamon

- .github/workflows/ci.yml
- requirements-test.txt
Add  codcov reports. This can help inform us of uncovered branches and help with investigating bugs.
> Add coverage report to CI

- arroyo/backends/kafka/configuration.py
This is just wrong since it doesn't include all options
> feat: Remove pointless (and wrong) config check

- .github/workflows/ci.yml
- requirements-test.txt
This reverts commit 0d7a0ec5afae584b8bdc3571d4ae656f4864a870.
Codecov is reporting the wrong thing. This is blocking the release process.
> Revert "Add coverage report to CI (#286)"

- arroyo/backends/kafka/commit.py
- tests/backends/test_commit.py
I really don't want to port this abomination to Rust, let's simplify the commit log format
Two main changes:
- uses float instead of weird datetime format we had before
- avoids putting important information in headers. This was a hack to avoid changing the message format earlier, but it should be avoided. The timestamp is now in the payload of the message
This is the first of 3 changes, encode method is unchanged, the decode method supports the new format.
> ref: A better commit log format

- arroyo/backends/kafka/commit.py
- tests/backends/test_commit.py
Follow up to https://github.com/getsentry/arroyo/pull/289
> ref: A better commit log format pt2

- arroyo/backends/kafka/commit.py
- arroyo/commit.py
It was only this way for rollout, it's now there on all messages for years
> ref: Timestamp is not optional on commit log

- arroyo/processing/processor.py
- tests/processing/test_processor.py
This is the same fix we did in the Rust version of Arroyo https://github.com/getsentry/snuba/pull/4774
We saw a lot of performance improvements after this change so I'm porting it to Python too.
> perf: Avoid unnecessarily clearing the rdkafka buffer on backpressure

- arroyo/backends/kafka/commit.py
- tests/backends/test_commit.py
We experienced issues when deploying https://github.com/getsentry/arroyo/pull/295 to production. It was discovered that very old commit log entries are still present. This is likely because the commit log topic has cleanup.policy=compact set, which causes messages to never expire if they have a unique key.
The process of fixing this is underway: https://github.com/getsentry/snuba/pull/4941 and https://github.com/getsentry/ops/pull/8361
However we have to keep support for the legacy commit log format around for a while until this work is complete.
> fix: Temporarily bring back support for legacy commit log format

- arroyo/processing/processor.py
This is a fix for inc-552
It caused a bug where a message could be submitted to the processing strategy twice immediately after assignment if there was backpressure before the rebalance.
> fix: Cleanup backpressure state between assignments

- arroyo/processing/strategies/run_task_with_multiprocessing.py
- tests/processing/strategies/test_run_task_with_multiprocessing.py
Invalid messages raised from strategies downstream of RunTaskWithMultiprocessing are not correctly handled currently. Currently messages from that batch will be re-submitted to the next step multiple times. This change ensures they are correctly re-raised and avoids the duplicate messages downstream.
> fix(dlq): RunTaskWithMultiprocessing supports forwarding downstream invalid message

- arroyo/processing/processor.py
- arroyo/utils/metric_defs.py
- tests/processing/test_processor.py
Rename `arroyo.consumer.paused.time` to `arroyo.consumer.backpressure.time`
Two main motivations for this:
- The new metric matches the name emitted by the Rust consumer, we should align these exactly to make the transition smoother
- The consumer is no longer actually paused immediately when backpressure happens (we now wait until we are in the backpressure state for at least a second as pausing is expensive). So the old metric name is kind of misleading now.
> ref: Rename backpressure metric

- arroyo/processing/processor.py
- tests/processing/test_processor.py
Alternative to https://github.com/getsentry/arroyo/pull/304
We occasionally see this invalid state error in prod. This poll/assertion is kind of pointless anyway, let's remove it.
> fix: Attempt to fix InvalidStateError

- arroyo/processing/strategies/run_task_with_multiprocessing.py
- tests/processing/strategies/test_run_task_with_multiprocessing.py
We were under the assumption that we can pick an arbitrarily low value
here since it will be automatically resized. However, in the case where
a single message is larger than the block size, the consumer can still
crash.
This is too hard to fix right now and not worth it, so hardcode it to
16M (which is more than the max Kafka message size), and hope it never
happens again.
The original purpose of dynamically resizing input blocks was to make
performance tuning simpler, and IMO we still have achieved that.
> fix: Default input block size should be larger

- arroyo/processing/strategies/commit.py
- arroyo/processing/strategies/produce.py
- arroyo/processing/strategies/reduce.py
- arroyo/processing/strategies/unfold.py
- arroyo/types.py
- arroyo/utils/metric_defs.py
- examples/transform_and_produce/batched.py
- tests/processing/strategies/test_all.py
- tests/processing/strategies/test_batching.py
- tests/processing/strategies/test_commit.py
- tests/processing/strategies/test_filter.py
- tests/processing/strategies/test_guard.py
- tests/processing/strategies/test_produce.py
- tests/processing/strategies/test_reduce.py
- tests/processing/strategies/test_run_task.py
- tests/processing/strategies/test_run_task_with_multiprocessing.py
- tests/processing/strategies/test_unfold.py
- tests/processing/test_processor.py
- tests/test_types.py
The goal of this change is to record a common latency metric for all consumers that use Arroyo.
The new metric is called `arroyo.consumer.latency` -- it represents the time in seconds from when the message was initially produced (broker timestamp) to when the consumer successfully committed the offset for a message.
Note that if a consumer is doing either manual batching (not using Arroyo's built in Reduce/Batch) or manual committing of offsets (not using Arroyo's CommitOffsets strategy), then the metric will not be recorded automatically.
Closes https://github.com/getsentry/arroyo/issues/307
> feat: Enable automatic latency recording for consumers

- arroyo/dlq.py
- arroyo/processing/processor.py
- tests/test_dlq.py
While working on porting this code to the Rust consumer, I noticed that the DLQ limits are not working in Python as expected. This is an attempt to fix that. Specifically, limits are being ignored. Even if one is defined, the Arroyo processor behaves as if there was no limit set and simply forwards all invalid messages to the DLQ.
> fix(dlq): Actually respect the DLQ limits

- arroyo/dlq.py
- tests/test_dlq.py
This aligns `DlqLimitState` with the Rust implementation in https://github.com/getsentry/snuba/pull/5156. To wit:
* `update_invalid_value` and `should_accept` are combined into `record_invalid_message`, since they're never called independently.
* We insert some default data if we've never received an invalid message on a partition.
> ref: Combine DlqLimitState methods

- arroyo/processing/strategies/run_task_with_multiprocessing.py
- tests/processing/strategies/test_all.py
- tests/processing/strategies/test_run_task_with_multiprocessing.py
The `RunTaskWithMultiprocessing` strategy now takes a `MultiprocessingPool` as an argument. The user can safely reuse the multiprocessing pool between rebalances. Recreating the pool each time is still also possible and would match today's behavior.
> feat: Reusable multiprocessing pool

- arroyo/processing/strategies/filter.py
- arroyo/types.py
- tests/processing/strategies/test_filter.py
When joining a FilterStep, it can happen that the upstream strategy
raises MessageRejected. We need to deal with that somehow, and in this
PR I'm just suppressing that exception.
Also fix a severe bug where MessageRejected was propagated through
submit(), but the MessageRejected was for the wrong message, causing
double-submission of messages.
> fix(filter): Handle MessageRejected correctly (INC-584)

- arroyo/processing/strategies/run_task_with_multiprocessing.py
- arroyo/utils/metric_defs.py
- tests/processing/strategies/test_run_task_with_multiprocessing.py
If multiprocessing tasks are not completed within the timeout specified, we need to reset the pool to avoid state being carried over between assignments.
> fix(multiprocessing): Reset pool if tasks are not completed

- arroyo/processing/strategies/commit.py
This should be a timing metric not a counter
> fix: Make `arroyo.consumer.latency` a timing metric

- arroyo/processing/strategies/run_task_with_multiprocessing.py
- tests/processing/strategies/test_run_task_with_multiprocessing.py
See INC-594 -- in a later TT role-playing exercise, it became apparent
that this error message is suboptimal, in that it neither tells you
whether input or output is overflowing, and what parameter to tweak
> fix(multiprocessing): Implement better error messages for block overflow

- rust-arroyo/src/processing/strategies/reduce.rs
We can also later decide to change the Python metric, but then we would
have to fix dashboards outside of Snuba.
> fix: Rename Rust arroyo metric since it has a different unit [SNS-2605]

- rust-arroyo/src/processing/mod.rs
Adding this info as it can be very helpful for debugging discrepancies between partitions and the associated consumers
> feat(logs): Add partition info upon assignment and revocation

- arroyo/processing/strategies/buffer.py
- arroyo/processing/strategies/healthcheck.py
- arroyo/processing/strategies/reduce.py
- arroyo/processing/strategies/reduce_new.py
- tests/processing/strategies/test_batching.py
- tests/processing/strategies/test_buffer.py
The pull is documented in the code.  Its more contextual to read the reasoning there.  Mostly the buffer protocol and the flush method.  The buffer impl is totally independent of Arroyo/Kafka all the rest.  You can write a buffer with no knowledge of where it will be used.
- Adds the concept of a Buffer protocol.
- Moves all Kafka specific behavior out of the buffer protocol and into the strategy class.
- Allows for flexible buffering without constraint.
> Add flexible Reduce strategy type

- rust-arroyo/src/utils/timing.rs
This particular change reduces the overall execution time of `snuba-queries/1/rate-limited-real.json` from 9.3% to 5.8%, because it wasn't inlined.
I basically run the following command to create some traffic for local benchmarking:
```
❯ yes "$(cat ../sentry-kafka-schemas/examples/snuba-queries/1/rate-limited-real.json | jq -c .)" | head -10000 | kcat -P -b 127.0.0.1:9092 -t snuba-queries
```
> perf: inline now calling `coarsetime::Instant`

- arroyo/processing/processor.py
- rust-arroyo/src/processing/mod.rs
- tests/processing/test_processor.py
During inc-626 we saw excessive backpressure which caused the consumer to be paused and resumed a lot. This led to excessive network traffic as the local queue was purged and messages were re-downloaded. Increase the threshold for pausing to reduce the impact of this.
> feat: Increase backpressure threshold to 5 seconds

- requirements.txt
No notable changes in the changelog that affects features used at sentry: https://github.com/confluentinc/confluent-kafka-python/releases
> feat: confluent-kafka-python 2.3.0

- rust-arroyo/src/processing/strategies/reduce.rs
The ergonomics are slightly worse, but I am in a position right now
where the value absolutely cannot be cloneable, and working around those
trait constraints would be even less ergonomical.
> ref(reduce): Allow to reduce to non-cloneable values

- arroyo/backends/kafka/configuration.py
- rust-arroyo/src/backends/kafka/mod.rs
error is undesirable most of the time and is not a good default. it can cause downtime when doing things like scaling partitions as the new partitions will error thus crashlooping the consumer. this happened in inc-702
> feat: make default auto.offset.reset earliest

- rust-arroyo/src/backends/kafka/types.rs
Add the ability in the Headers struct of types to be able to find a key and if found return the corresponding value.
> feat(header): Implement find method on headers

- arroyo/backends/abstract.py
- arroyo/backends/kafka/consumer.py
- arroyo/backends/local/backend.py
- arroyo/processing/processor.py
- rust-arroyo/src/backends/kafka/mod.rs
- rust-arroyo/src/processing/mod.rs
Adds more logging to rust to more closely match python. Specifically, we add logging to show when the processor is terminating or closing/rejoining strategies.
We also introduce logging to show the member id as supplied by the broker. This is useful for debugging issue related to rebalancing in kafka since the broker logs only show member id.
> rust: add more rust logging

- rust-arroyo/src/processing/strategies/reduce.rs
Slightly simplify the logic so that timeout=0 is honored.
Needed for https://github.com/getsentry/team-sns/issues/4
> ref(reduce): Refactor for timeout=0

- rust-arroyo/src/processing/strategies/run_task_in_threads.rs
It's hard to tell which strategy is the bottleneck, but we have a lot of
different threadpools in the snuba rust consumers who all could be it.
Emit backpressure metrics for both getting and receiving backpressure,
it will help figuring out which strategy causes the most backpressure.
> ref(rust): Backpressure metrics for threadpools

- rust-arroyo/examples/base_processor.rs
- rust-arroyo/src/metrics/types.rs
- rust-arroyo/src/processing/mod.rs
- rust-arroyo/src/processing/strategies/commit_offsets.rs
- rust-arroyo/src/utils/timing.rs
coarsetime is a crate that allows you to fetch the current time with an
in-memory cache. This tends to be faster than actually getting the
current time.
Previously we were using Instant::now_without_update, which does not
actually give us any perf benefits. Let's use ::recent everywhere and
update the timestamp in the StreamProcessor.
> ref: Use coarsetime consistently

- arroyo/processing/strategies/produce.py
- tests/processing/strategies/test_produce.py
> fix: add guard to Produce.poll to ensure next_step is called regardless of produce queue

- arroyo/processing/strategies/noop.py
- docs/source/strategies/index.rst
- docs/source/strategies/noop.rst
- rust-arroyo/examples/transform_and_produce.rs
- rust-arroyo/src/processing/strategies/mod.rs
- rust-arroyo/src/processing/strategies/noop.rs
- rust-arroyo/src/processing/strategies/produce.rs
- rust-arroyo/src/processing/strategies/run_task.rs
- tests/processing/strategies/test_noop.py
This can be useful when you consume a message and do not wish to commit he offset back to Kafka [1].
[1]: The sentry uptime-checker project has this requirement as it is using Kafka as a mechanism to store configurations. By using log compaction we never actually want to commit a log offset, and want to read the entire log every time.
> feat: Add Noop processing strategy

- rust-arroyo/src/processing/dlq.rs
We can also measure the length of the queue, but as far as I can tell `VecDeque` only really has the `capacity()` function. 
If we see this metric drop to 0 and then spike up to a new very high value, we would be able to detect the scenario where the buffer is being reallocated. Not sure if we need anything more complicated than this since we have the mutable buffer being accessed in both of these functions anyways and we can just check in these functions. 
Also tracks the number of partitions in the BTreeMap
> Add a basic metric for tracking the capacity in VecDeque buffer

- CODEOWNERS
`@getsentry/processing` no longer exists and it showed the following error in the CODEOWNERS:
The same team was removed from Snuba's codeowners previously: https://github.com/getsentry/snuba/pull/6259#discussion_r1741202790
> Remove non-existent @getsentry/processing from CODEOWNERS

- arroyo/processing/processor.py
- arroyo/processing/strategies/batching.py
- arroyo/processing/strategies/unfold.py
- tests/processing/strategies/test_batching.py
- tests/processing/strategies/test_unfold.py
This PR aligns the `Unbatch` and `Unfold` strategies to the behavior of their counterparts `Batch` and `Reduce`. 
`Unbatch` now just submits the values of a submitted `ValuesBatch` one after another to the next step. Therefore, the logic  was reduced to rely fully on the passed generator function for building a `Message`'s `Value`.   
I tried my best fixing the typing issues but there is still one in `arroyo/processing/strategies/batching.py:116` with which I had no luck.
Closes  #369
> fix: Allow sending committable from Unfold

- rust-arroyo/examples/transform_and_produce.rs
- rust-arroyo/src/processing/dlq.rs
- rust-arroyo/src/processing/strategies/commit_offsets.rs
- rust-arroyo/src/processing/strategies/mod.rs
- rust-arroyo/src/processing/strategies/run_task.rs
This will allow you to use mutable state from within RunTask where
previously one couldn't, and remove some boilerplate
Also fix a warning drive-by.
> ref(rust/run_task): Remove unnecessary boxing, make FnMut, change return type

- arroyo/processing/processor.py
- arroyo/processing/strategies/batching.py
- arroyo/processing/strategies/reduce.py
- tests/processing/strategies/test_batching.py
I wanted to be able to batch by an amount other than just the count of messages. I have this implement in https://github.com/getsentry/snuba/pull/6510/, but it's a lot of copying from arroyo, so it would be nice to have it baked into here. ~I'm not sure if we have a ton of other uses for it, but it also seems like it would be relatively harmless to add since by default the batching works the same as before~
Looks like the rust implementation already has something similar (`compute_batch_size`) added in https://github.com/getsentry/arroyo/commit/a5087b8c715c1602b9bd18e3e6a810a97da0988a
> ref(batching): add compute_batch_size to BatchStep

- rust-arroyo/src/processing/strategies/produce.rs
- rust-arroyo/src/processing/strategies/run_task_in_threads.rs
We already did this change for a bunch of other strategies, but
RunTaskInThreads was missing it.
Boxing is still possible, but not required. And when you don't use it,
it's gonna be faster.
> Remove box from RunTaskInThreads

- rust-arroyo/src/processing/dlq.rs
This buffer is tracked per partition. Add partition as a tag to see the breakdown.
> metric: Add partition tag to DLQ buffer capacity metric

- rust-arroyo/src/processing/dlq.rs
When no DLQ topic is configured, arroyo will not create a DLQ policy,
which in turn will leave us with an unbounded DLQ buffer.
> fix(dlq): Set limit correctly if no dlq-topic is configured

- rust-arroyo/src/processing/dlq.rs
- rust-arroyo/src/processing/mod.rs
If the DLQ is disabled, we can save cloning of the message entirely,
saving 1 allocation
> fix(dlq): Do not clone the message if the DLQ is disabled.

- rust-arroyo/src/processing/dlq.rs
- rust-arroyo/src/processing/mod.rs
- rust-arroyo/src/testutils.rs
The goal of this PR is to make all DLQ buffer management happen through DLQ policy.
Specifically:
- Ensure no DLQ buffer gets created if there is no DLQ policy defined
- Adding, removing messages to/from buffer goes through DLQ policy
- Log better errors if there are Invalid Messages but no DLQ policy defined
The next step after this refactor is to clear DLQ buffer during rebalancing. This refactor makes it so that we can access the DLQ buffer within the `on_assign` or `on_revoke` callbacks.
> ref(dlq): Move DLQ buffer into DLQ policy

- arroyo/backends/kafka/commit.py
- arroyo/utils/clock.py
- tests/backends/test_local.py
- tests/conftest.py
- tests/processing/strategies/test_produce.py
- tests/processing/test_processor.py
- tests/utils/test_retries.py
pytest complains about the name TestingClock
logger.warn is deprecated in favor of logger.warning
> chore: Fix a few warnings

- arroyo/backends/kafka/consumer.py
- arroyo/dlq.py
- arroyo/processing/processor.py
- pytest.ini
- tests/backends/mixins.py
- tests/backends/test_kafka.py
- tests/processing/test_processor.py
- tests/test_dlq.py
Fix one bug in StreamProcessor where it assumed the passed assignments
are replacing the old ones.
Our consumer backends mostly work as-is, and are already passing the
right values in callbacks.
> feat: Initial support for cooperative-sticky rebalancing

- arroyo/processing/processor.py
There is a bug in StreamProcessor where self.__is_paused, but at the
same time we poll the consumer and get messages.
File "sentry/runner/commands/run.py", line 455, in basic_consumer
run_processor_with_signals(processor, consumer_name)
File "sentry/utils/kafka.py", line 46, in run_processor_with_signals
processor.run()
File "arroyo/processing/processor.py", line 323, in run
self._run_once()
File "arroyo/processing/processor.py", line 442, in _run_once
assert self.__consumer.poll(0.1) is None
Breadcrumbs indicate that rebalancing was happening at that time. Could
it be that we were paused, but the consumer got more partitions
assigned? It doesn't make sense since we don't have cooperative-sticky
rebalancing enabled, let's add more logs and prevent the crash.
related: …
> fix: Avoid polling the consumer if it says it's paused

- arroyo/dlq.py
- arroyo/processing/processor.py
this enables a user to choose whether an invalid message exception is logged or not
default is unchanged and does log the exception
for stale messages we don't want to log them, we will just reroute to the lowpri topic
> perf: invalid message logging configuration

- arroyo/dlq.py
- rust-arroyo/src/processing/dlq.rs
for our high throughput consumers (which do >1000 messages/sec), this is too small
it's important not to drop messages as we are going to be using dlq more for stale messages too
fixes SENTRY-FOR-SENTRY-A1Z
> fix: increase dlq buffer size

- arroyo/processing/processor.py
- arroyo/utils/metric_defs.py
- tests/processing/test_processor.py
Right now, if the produce fails for any reason, the consumer backlogs, allow graceful degradation instead
> fix(inc-1013): Don't fail the consumer when the DLQ produce fails

- arroyo/dlq.py
- arroyo/utils/metric_defs.py
We had these in Rust-arroyo but not in python
Add metrics to track the length of the DLQ deque
> dlq: Add metrics on DLQ buffer to python-arroyo

- .pre-commit-config.yaml
- arroyo/processing/strategies/unfold.py
- tests/processing/strategies/test_unfold.py
In https://github.com/getsentry/arroyo/pull/371 we changed the API for
Unfold to allow for custom committable. However, we also made it
mandatory to figure out a committable at all in order for committing to
work.
The callbacks for unfold do not get access to the original committable,
so it's actually not possible to satisfy the 99% usecase with this.
cc @mj0nez
> fix(unfold): Do not forward empty committable

- arroyo/dlq.py
- arroyo/utils/metric_defs.py
the previous way was creating too many logs slowing the consumer down and filling up gcp logs. this is the same as #422 but for python.
> fix: fix logging for dlq buffer exceeded

- arroyo/dlq.py
- arroyo/utils/metric_defs.py
> metric: Track the number of partitions in the DLQ buffer

- arroyo/processing/strategies/unfold.py
- tests/processing/strategies/test_unfold.py
`poll()` can block the main thread when backpressure lasts "forever", such as when unfolding a particularly huge array. Instead, let's exit early and forward the backpressure.
> fix(unfold): Do not block forever on backpressure

- .flake8
- .pre-commit-config.yaml
- arroyo/backends/abstract.py
- arroyo/backends/kafka/consumer.py
- arroyo/dlq.py
- arroyo/processing/processor.py
- arroyo/processing/strategies/produce.py
- tests/backends/test_kafka.py
- tests/processing/test_processor.py
When producing a large amount of messages, it can be that the profile
consists only of `Future()` calls, and most of the time is being spent
on running that ctor.
When you look inside of Future.__init__, all it does is create
threading.Condition so that `result()` can be blocking.
However, in the Produce step, we do not actually need synchronized
access to the future, nor do we need to have a blocking result(). We
only need done() and non-blocking result().
Introduce ab abstract interface for futures that is fulfilled by stdlib
Future() and a new class that does not offer performant result().
The new future type is not enabled by default as we have uses of the
`Producer` in sentry that do use the full `Future` interface (see `SingletonProducer`)
> ref(produce): Add faster way to produce

- arroyo/processing/strategies/run_task_with_multiprocessing.py
- tests/processing/strategies/test_run_task_with_multiprocessing.py
~technically this should probably be a context manager but it seems to use java-like `.close()` pattern instead and I'm not about to try and fix every caller
> avoid leaking SIGCHLD handler in RunTaskWithMultiprocessing

- tests/processing/test_processor.py
If the consumer is paused, and is carrying over a message, and then that same message ends up being Invalid, the consumer gets stuck forever. It never leaves the paused state. 
This unit test demonstrates this failure mode. A following PR will introduce a fix and an adjustment to this unit test.
> inc: Add a unit test that demonstrates InvalidMessage failure mode

- arroyo/processing/strategies/run_task_with_multiprocessing.py
- tests/processing/strategies/test_run_task_with_multiprocessing.py
`RunTaskWithMultiprocessing` constructs exactly one pair of input and output blocks per process. Once a process has finished a block, it has to wait for the strategy to poll and submit to the next step, then reclaim the input block, have it filled by the previous step, and resubmit it into the pool. As long as the steps before and after multi processing are free or cheap, this is not big of a deal, but once they consume more time, it leads to idle time in the process pool. 
Even if the main thread is not the bottle neck, this idle time leads to lower throughput per process than possible. Assuming a consumer is limited by pool throughput - a fair assumption - the goal should be to maximize processing time in the pool and minimize the time processes wait for new work.
This PR attempts to …
> ref(multi-process): Double block count to saturate sub processes

- rust-arroyo/src/processing/strategies/run_task_in_threads.rs
Adds more metrics so we can easily see where the backpressure is getting raised from
> INC-1119: add more metrics for back pressure

- requirements.txt
It sems the recently released confluent-kafka 2.10.0 is breaking
several of our KIP848 tests. 
Limiting the version range while we fix them.
> Limit the confluent library version

- arroyo/processing/processor.py
Attempted fix for #357
[DACI](https://www.notion.so/DACI-Improved-kafka-consumer-metrics-a3828b53d0554ddcb2ed67f4d0c89f83)
Starting with the metrics most important for understanding consumer balancing across a group, but it may make sense to include this tag on other consumer-related metrics as well. Can be done in a follow up.
**Questions**
> add consumer_member_id tag to partitions assign / revoked metrics

- arroyo/processing/processor.py
- arroyo/utils/metrics.py
- tests/utils/test_metrics.py
Fixes #357 
This PR automatically adds `consumer_member_id` tags to all consumer-related metrics, improving observability and debugging capabilities in distributed consumer environments.
> feat: add consumer_member_id to metrics by default

- arroyo/processing/processor.py
- arroyo/utils/metrics.py
- tests/utils/test_metrics.py
The member ID tag is set too early to a static value.
ref STREAMING-30
> fix(metrics): Re-set consumer member ID tag after every partition assignment

- Cargo.toml
- rust-arroyo/src/backends/kafka/mod.rs
This allows us to upgrade the SDK in crates that depend on both the SDK and `arroyo` itself, and not end up with two separate versions in the lockfile and at runtime.
Additionally, we just need to depend on `sentry_core`, as the only functionality we're using here is the `Hub`.
Ref https://github.com/getsentry/snuba/pull/7250
> chore(deps): depend on sentry-core >=0.32

- rust-arroyo/src/backends/kafka/errors.rs
- rust-arroyo/src/backends/kafka/producer.rs
- rust-arroyo/src/backends/mod.rs
- rust-arroyo/src/processing/strategies/produce.rs
This adds the error codes to the producer failure metric in Rust. Some new producer errors were also
added that explicitly deal with producing (similar to the consumer errors).
> fix(slo): Add error codes to producer failure in Rust

- rust-arroyo/src/backends/kafka/errors.rs
- rust-arroyo/src/backends/kafka/producer.rs
- rust-arroyo/src/backends/local/mod.rs
- rust-arroyo/src/backends/mod.rs
- rust-arroyo/src/processing/strategies/produce.rs
Instead of trying to log metrics at the strategy level, instead log the metrics in the Producer.
This has two advantages:
- The Kafka callback can be used to capture all errors
- Metrics will be collected for those producers that don't use the strategy
> fix(metrics): Log producer metrics in the callback

- arroyo/processing/strategies/run_task_with_multiprocessing.py
From production logs it seems we are missing the first log line (start of the multiprocess initializer). 
This is likely because the initializer also configures the logger.
Adding the elapsed time to the log at the end of the function call.
> Add elapsed time to the Multiprocess init log
