.pre-commit-config.yaml, Makefile, setup.py
Using Black's default line length of 88
=> feat: Add pre-commit with code style defaults and type checking

CODEOWNERS
Designated codeowner will be required to review pull requests before merging
=> meta: Add CODEOWNERS

.flake8
Add the same flake8 configuration as Snuba
=> build: Use Snuba's flake8 configuration

CHANGELOG.md
Add versioning policy that is similar to other Sentry projects
=> meta: Add versioning policy

CHANGELOG.md
=> Add changelog for previous pr

.github/workflows/release.yml
Like https://github.com/getsentry/snuba-sdk/pull/81
=> fix(ci): Checkout full repo history for craft

arroyo/processing/strategies/streaming/collect.py
Added metrics to account for time spent polling and closing and resetting of batch to observe the current behavior and possible improvements with parallel collect.
=> ref(metrics): Add metrics for time spent polling and closing batch

.github/workflows/ci.yml
We'll want to support these versions eventually. Let's see if this works.
=> feat: Run CI on multiple Python versions

tests/processing/strategies/test_streaming.py
ARM-based Macs use a 16K page size, so any block of shared memory will be
at least this size, regardless of size actually requested. (Intel machines
use a 4K page size instead.)
Change tests that allocate shared memory to do so in multiples of 16K so
that these tests behave the same regardless of machine architecture, and
update the sizes used by test data accordingly.
=> fix(tests): Make tests pass on M1 Macs

.github/codeql/codeql-config.yml, .github/workflows/codeql-analysis.yml
Configures CodeQL to run once a week.
=> Configure CodeQL

.github/workflows/docs-pr.yml, .github/workflows/docs.yml, docs/source/getstarted.rst, docs/source/index.rst, docs/source/intro.rst
Adds a simple tutorial that shows how to create a ProcessingStrategy
=> feat(docs) Add a `getting started` page to the docs

MANIFEST.in
=> build: Include requirements.txt in source distribution

arroyo/processing/strategies/produce.py
We were storing entire messages in the queue of the produce step just so we know what offset to commit once the future is done. Since the messages can be quite large and the queue quite long this seems wasteful. Now we are just storing the parts we actually need to commit.
=> feat: Avoid storing entire messages in the produce step

arroyo/processing/strategies/run_task.py
Same as https://github.com/getsentry/arroyo/pull/132 but for RunTaskInThreads. No need to store extra copies of entire messages here just for committing.
=> feat: Avoid storing entire messages in RunTaskInThreads

docs/source/dlq.rst, docs/source/index.rst, docs/source/strategies.rst
Add a warning that DLQ is subject to change. Also moves  DLQ docs under processing strategies
=> docs: Update DLQ docs

arroyo/backends/abstract.py, arroyo/backends/kafka/consumer.py, arroyo/backends/local/backend.py, arroyo/backends/local/storages/abstract.py, arroyo/backends/local/storages/file.py, arroyo/backends/local/storages/memory.py, arroyo/processing/processor.py, arroyo/processing/strategies/batching.py, arroyo/processing/strategies/collect.py, arroyo/processing/strategies/commit.py, arroyo/processing/strategies/dead_letter_queue/policies/produce.py, arroyo/processing/strategies/produce.py, arroyo/processing/strategies/run_task.py, arroyo/processing/strategies/transform.py, arroyo/types.py, tests/backends/mixins.py, tests/backends/test_kafka.py, tests/processing/strategies/test_batching.py, tests/processing/strategies/test_collect.py, tests/processing/strategies/test_commit.py, tests/processing/strategies/test_dead_letter_queue.py, tests/processing/strategies/test_filter.py, tests/processing/strategies/test_produce.py, tests/processing/strategies/test_run_task.py, tests/processing/strategies/test_transform.py, tests/processing/test_processor.py, tests/test_types.py
Includes the following changes:
- https://github.com/getsentry/arroyo/pull/134
This branch will be used for 2.x releases.
Will be merged once we have updated to 2.0.0 everywhere and are confident we no longer want to support further 1.x releases
=> feat: Arroyo 2.0.0 changes

arroyo/processing/strategies/reduce.py
Same as `collect.reset_batch` but for the reduce step. We had the previous metric on one of our dashboards but lost it when switching the implementation to use reduce. Let's bring back an equivalent as it can be useful to keep track of actual batch sizes.
=> feat(reduce): Record `arroyo.strategies.reduce.batch_time`

docs/source/getstarted.rst, docs/source/what_for.rst
Fix a typo and improve formatting.
=> fix: Documentation typos

.pre-commit-config.yaml
https://github.com/python-poetry/poetry-core/pull/542
Committed via https://github.com/asottile/all-repos
=> ref: upgrade isort to work around poetry breakage 

arroyo/processing/strategies/reduce.py
We forgot to call next_step.close()
=> fix(reduce): Ensure next step is properly closed

.gitignore, docs/source/architecture.rst
Was reading this and saw some minor grammar mistakes and small word improvements. Also added `.idea` pycharm IDE project director to gitignore.
=> doc: small grammar improvements

docs/source/getstarted.rst
We no longer recommend most users define their own strategies as we provide a lot more generic strategies now that cover most message processing use cases. Let's not suggest this path in getting started any more.
=> docs: Update get started section

arroyo/dlq.py, docs/source/dlqs.rst, docs/source/index.rst
This change only introduces some of the classes that will be needed by the DLQ and adds documentation that describes how it will eventually work. This feature is a work in progress and it doesn't necessarily work this way yet!
=> feat(dlq): Introduce DLQ docs and interfaces

arroyo/dlq.py
So it can be plugged into the stream processor
=> feat(dlq): Make dlq interface generic

arroyo/processing/processor.py
We are seeing that a big chunk is missing from the consumer time
breakdown. Let's see where all this stuff went.
=> feat: Add consumer dlq time

arroyo/processing/processor.py, tests/processing/test_processor.py
See SNS-2258
As part of resolving INC-344, we are still trying to figure out whether
the consumer was spinning and hogging the GIL of the main thread, and
whether that was responsible for the consumer grinding to a halt and
therefore the root cause of the incident.
Let's just put a metric in to see how often arroyo spins. While we are
"pretty sure" that the consumer spins, we are not sure about it being
the root cause, and IMO confidence as to whether it even happened can be
higher. Afaik the only indicator we have is elevated CPU usage (could
have been caused by something else) and increased pause time.
=> feat: Count how many times consumer spins

tests/processing/strategies/test_run_task_with_multiprocessing.py
This test is flaky because it polls for 5 times and assumes that 5
messages get processed in that time. The test below is a duplicate
recently added that doesn't have this problem.
=> fix: Remove flaky test

arroyo/backends/kafka/configuration.py, arroyo/utils/metric_defs.py
I don't think there's value in tweaking how often this metric gets
reported, let's just hardcode everything.
=> feat: Basic support for librdkafka stats

arroyo/backends/kafka/consumer.py
I don't think this even needs to be configurable. Let's just pick a better default. This particular default is ported from the Snuba consumer.
=> feat: A better default retry policy

requirements.txt
https://github.com/confluentinc/confluent-kafka-python/blob/master/CHANGELOG.md
=> feat: Bump confluent-kafka-python from 1.9.0 to 2.1.1

docs/source/what_for.rst
I think this isn't true anymore - since this was written most of the committing logic has been changed so the user never calls commit manually anymore.
=> docs: Update goals

arroyo/processing/strategies/healthcheck.py
Add polling the next step in the healthcheck poll
=> fix(healthcheck): poll in healthcheck

arroyo/dlq.py
In the case where all messages on the kafka pipeline are bad, it is possible that there is no valid message. Today, the code would crash because of division by zero error. Instead, we should reject the messages and let the consumers backlog because zero valid messages indicates systemic problems in the pipeline.
=> fix(dlq): Gracefully handle case of no valid messages

arroyo/processing/processor.py, arroyo/utils/metric_defs.py
We were logging these but let's add a metric as well.
=> feat(metrics): Add a metric for number of invalid messages encountered

arroyo/backends/kafka/commit.py
There is a mystery right now which is causing (probably) very old commit messages to still be present. This seems to be the case even after we switched the cleanup policy on the topic to `compact,delete` from `compact` in all environments so that messages eventually expire (they previously never expired). This adds some logging to help us figure out where/when these old messages came from and helps us determine when the legacy decoder can be safely removed.
=> ref: Add extra logging for debugging commits

CODEOWNERS
In snuba that used to be processing team and streaming team.
=> ref: Restore owners on rust-arroyo

.craft.yml
=> fix(release): Stop releasing to crates.io while it doesn't work

arroyo/utils/metric_defs.py
This line moved to the wrong place
=> ref: Metric definition

CODEOWNERS
This is also maintained by the ops team who should be able to approve these changes
=> meta: Update codeowners

rust-arroyo/src/processing/strategies/run_task_in_threads.rs
We suspect that joining a threadpool takes most of the time when
rebalancing.
=> ref(rust): Add join-time metric for threadpools

rust-arroyo/examples/transform_and_produce.rs, rust-arroyo/src/processing/strategies/run_task.rs
RunTask now more closely matches the python interface
=> Update RunTask to receive a Message<TPayload>

.github/workflows/build.yml, .github/workflows/ci.yml, .gitignore, arroyo/utils/metric_defs.py, docs/source/metrics.rst, scripts/create_metrics_def_json.py, setup.py
This PR adds a script which parses the implemented metric definitions and saves them as a machine readable file. To allow downstream consumers automatic updates on new Arroyo versions, it was integrated into the package build process and will ship with future versions.
Closes #360
=> feat: enhance metrics defs

.craft.yml, Cargo.toml, rust-arroyo/examples/base_consumer.rs, rust-arroyo/examples/base_processor.rs, rust-arroyo/examples/transform_and_produce.rs
arroyo is taken, rust_arroyo is a dumb name, let's use sentry_arroyo
=> chore: Preparations for publishing the Rust crate

arroyo/dlq.py
the emitted metric `arroyo.consumer.dlq_buffer.len` did not have `partition_index` as a tag which meant we couldnt split it up by partition, which we want to do. This adds it.
=> feat: add partition_index tag to dlq metric

.github/workflows/docs-pr.yml, .github/workflows/docs.yml, arroyo/backends/abstract.py, tests/backends/test_kafka.py
Reverts getsentry/arroyo#441
Can't bump Arroyo version right now in Sentry as there are some typing issues, we can come back to it afterwards
=> Revert "ref(producer): Simplify typing, add more tests"

arroyo/processing/strategies/produce.py, arroyo/utils/metric_defs.py, rust-arroyo/src/processing/strategies/produce.rs
This adds a metric that counts how many successful produces there were with a status. A future PR
will also add the specific error code to the tags.
=> fix(slo): Add a metric to capture produce success/failures for our SLO

arroyo/processing/strategies/produce.py
If the exception is a KafkaException, add the error code to the metric produced.
=> fix(metrics): Add an error code to the produce SLO

requirements-test.txt, tests/processing/test_processor.py
Remove a few deprecation warnings from output
=> ref: Bump pytest

arroyo/backends/kafka/configuration.py, arroyo/backends/kafka/consumer.py, arroyo/utils/metric_defs.py, rust-arroyo/src/backends/kafka/config.rs, rust-arroyo/src/backends/kafka/producer.rs, tests/backends/test_kafka_producer.py
ref STREAM-324
See https://github.com/getsentry/relay/pull/5031 for context
=> ref: Add more metrics and producer_name tag

rust-arroyo/src/backends/kafka/mod.rs
Adding these metrics to be able to keep track of rdkafka fetch size
=> feat: Add metrics for fetch queue count and size
